package info.jab.testing.acceptance;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

final class TestDatabaseFixture implements AutoCloseable {

    private static final DockerImageName POSTGRES_IMAGE = DockerImageName.parse("postgres:17-alpine");

    private final PostgreSQLContainer<?> postgres;

    private TestDatabaseFixture(PostgreSQLContainer<?> postgres) {
        this.postgres = postgres;
    }

    static TestDatabaseFixture start() throws SQLException {
        PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>(POSTGRES_IMAGE)
            .withDatabaseName("customer_registration")
            .withUsername("acceptance")
            .withPassword("acceptance");
        postgres.start();

        TestDatabaseFixture fixture = new TestDatabaseFixture(postgres);
        fixture.createSchema();
        return fixture;
    }

    String jdbcUrl() {
        return postgres.getJdbcUrl();
    }

    String username() {
        return postgres.getUsername();
    }

    String password() {
        return postgres.getPassword();
    }

    void clearCustomers() throws SQLException {
        try (Connection connection = DriverManager.getConnection(jdbcUrl(), username(), password());
            Statement statement = connection.createStatement()) {
            statement.execute("delete from customers");
        }
    }

    int customerCount() throws SQLException {
        try (Connection connection = DriverManager.getConnection(jdbcUrl(), username(), password());
            Statement statement = connection.createStatement();
            var resultSet = statement.executeQuery("select count(*) from customers")) {
            resultSet.next();
            return resultSet.getInt(1);
        }
    }

    private void createSchema() throws SQLException {
        try (Connection connection = DriverManager.getConnection(jdbcUrl(), username(), password());
            Statement statement = connection.createStatement()) {
            statement.execute("""
                create table customers (
                    id bigint generated by default as identity primary key,
                    email varchar(320) not null,
                    name varchar(200) not null,
                    risk_decision varchar(40) not null
                )
                """);
        }
    }

    @Override
    public void close() {
        postgres.stop();
    }
}
