@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Cursor Rules Generator - Component Diagram

Container_Boundary(gen, "Generator (Java)") {
  Component(loader, "Resource Loader", "Classpath IO", "Loads XML, XSL, XSD resources")
  Component(xinclude, "XInclude Processor", "DOM Builder", "Resolves XInclude and builds DOM")
  Component(xsd, "XSD Validator", "SchemaFactory + XMLReader", "Validates XML against XSD (optional)")
  Component(xslt, "XSLT Transformer", "TransformerFactory", "Transforms XML to MDC via XSLT")
}

Rel(loader, xinclude, "Provides streams to")
Rel(xinclude, xsd, "Feeds SAX with validated XML")
Rel(xsd, xslt, "Supplies SAXSource for transformation")

@enduml

