openapi.info.title=Greek Gods REST API
openapi.info.description=API for retrieving information about Greek gods
openapi.info.version=1.0.0
openapi.info.contact.name=Juan Antonio Breña Moral
openapi.info.contact.email=my@email.com
openapi.info.license.name=Apache 2.0
openapi.info.license.url=https://www.apache.org/licenses/LICENSE-2.0
