name: Examples Build

on:
  push:
    paths:
      - "examples/**"

jobs:
  examples:
    name: Build Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - { name: "Maven", path: "examples/maven/maven-demo", goal: "verify", expectedExitCode: 0 }
          - { name: "Maven Invalid", path: "examples/maven/maven-demo-ko", goal: "validate", expectedExitCode: 1 }
          - { name: "Maven Multi Module", path: "examples/maven/maven-multi-module-demo", goal: "verify", expectedExitCode: 0 }
          - { name: "Profiling Spring Boot JMeter", path: "examples/profiling/spring-boot-jmeter-demo", goal: "verify", expectedExitCode: 0 }
          - { name: "Profiling Spring Boot Memory Leak", path: "examples/profiling/spring-boot-memory-leak-demo", goal: "package", expectedExitCode: 0 }
          - { name: "Profiling Spring Boot Performance Bottleneck", path: "examples/profiling/spring-boot-performance-bottleneck-demo", goal: "package", expectedExitCode: 0 }
          - { name: "Serverless AWS Lambda Hello World", path: "examples/serverless/aws-lambda-hello-world", goal: "verify", expectedExitCode: 0 }
          - { name: "Serverless Azure Function Hello World", path: "examples/serverless/azure-function-hello-world", goal: "verify", expectedExitCode: 0 }
          - { name: "Frameworks Spring Boot", path: "examples/frameworks/spring-boot", goal: "verify", expectedExitCode: 0 }
          - { name: "Frameworks Quarkus", path: "examples/frameworks/quarkus", goal: "verify", expectedExitCode: 0 }
          - { name: "Frameworks Micronaut", path: "examples/frameworks/micronaut", goal: "verify", expectedExitCode: 0 }
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true # Fetches all submodules
      - uses: actions/setup-java@v5
        with:
          distribution: "graalvm" # See 'Supported distributions' for available options
          java-version: "25"
      - name: Build ${{ matrix.example.name }}
        run: |
          cd "${{ matrix.example.path }}"
          set +e
          ./mvnw --batch-mode --no-transfer-progress ${{ matrix.example.goal }} --file pom.xml
          actual_exit_code=$?
          set -e

          expected_exit_code=${{ matrix.example.expectedExitCode }}
          if [ "${actual_exit_code}" -ne "${expected_exit_code}" ]; then
            echo "Expected exit code ${expected_exit_code}, got ${actual_exit_code}"
            exit 1
          fi

          echo "Maven command exited with expected code ${actual_exit_code}"
