name: Examples Build

on:
  push:
    paths:
      - "examples/**"

jobs:
  examples:
    name: Build Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - { name: "Maven", path: "examples/maven/maven-demo", goal: "verify" }
          - { name: "OpenSpec Requirements Problem 1", path: "examples/openspec/requirements-examples/problem1/implementation", goal: "verify" }
          - { name: "OpenSpec Spring Boot Demo", path: "examples/openspec/spring-boot-demo/implementation", goal: "verify" }
          - { name: "Profiling Spring Boot JMeter", path: "examples/profiling/spring-boot-jmeter-demo", goal: "verify" }
          - { name: "Profiling Spring Boot Memory Leak", path: "examples/profiling/spring-boot-memory-leak-demo", goal: "package" }
          - { name: "Profiling Spring Boot Performance Bottleneck", path: "examples/profiling/spring-boot-performance-bottleneck-demo", goal: "package" }
          - { name: "Serverless AWS Lambda Hello World", path: "examples/serverless/aws-lambda-hello-world", goal: "verify" }
          - { name: "Serverless Azure Function Hello World", path: "examples/serverless/azure-function-hello-world", goal: "verify" }
          - { name: "Frameworks Spring Boot", path: "examples/frameworks/spring-boot", goal: "verify" }
          - { name: "Frameworks Quarkus", path: "examples/frameworks/quarkus", goal: "verify" }
          - { name: "Frameworks Micronaut", path: "examples/frameworks/micronaut", goal: "verify" }
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true # Fetches all submodules
      - uses: actions/setup-java@v5
        with:
          distribution: "graalvm" # See 'Supported distributions' for available options
          java-version: "25"
      - name: Build ${{ matrix.example.name }}
        run: cd ${{ matrix.example.path }} && ./mvnw --batch-mode --no-transfer-progress ${{ matrix.example.goal }} --file pom.xml
