name: Examples Build

on:
  push:
    paths:
      - "examples/**"

jobs:
  examples:
    name: Build Examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - { name: "Maven", path: "examples/maven-demo", goal: "verify" }
          - { name: "Spring Boot Memory Leak", path: "examples/spring-boot-memory-leak-demo", goal: "package" }
          - { name: "Spring Boot Performance Bottleneck", path: "examples/spring-boot-performance-bottleneck-demo", goal: "package" }
          - { name: "Spring Boot", path: "examples/spring-boot-demo/implementation", goal: "verify -Pjacoco" }
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true # Fetches all submodules
      - uses: actions/setup-java@v5
        with:
          distribution: "graalvm" # See 'Supported distributions' for available options
          java-version: "25"
      - name: Build ${{ matrix.example.name }}
        run: cd ${{ matrix.example.path }} && ./mvnw --batch-mode --no-transfer-progress ${{ matrix.example.goal }} --file pom.xml
